export const mockBusiness = {
  id: "1",
  name: "ExpediaParts",
  slug: "expediaparts",
  website_url: "https://www.expediaparts.com",
  plan: "growth" as const,
  review_count: 2847,
  avg_rating: 4.9,
};

export const mockReviews = [
  {
    id: "r1",
    business_id: "1",
    customer_name: "Marcus T.",
    order_id: "ORD-48291",
    rating_overall: 5,
    review_text: "Exactly what I ordered. Fast shipping and the product matched the listing perfectly. Would buy again.",
    verified_purchase: true,
    fraud_score: 8,
    status: "published" as const,
    created_at: "2026-06-01T14:22:00Z",
  },
  {
    id: "r2",
    business_id: "1",
    customer_name: "Diane K.",
    order_id: "ORD-48102",
    rating_overall: 5,
    review_text: "Great quality and customer service responded within hours. Setup was straightforward.",
    verified_purchase: true,
    fraud_score: 12,
    status: "published" as const,
    business_response: "Thank you, Diane! We appreciate you taking the time to share your experience.",
    created_at: "2026-05-28T09:15:00Z",
  },
  {
    id: "r3",
    business_id: "1",
    customer_name: "Rafael S.",
    order_id: "ORD-47988",
    rating_overall: 4,
    review_text: "Solid product quality. Shipping took a day longer than expected but overall a good experience.",
    verified_purchase: true,
    fraud_score: 15,
    status: "published" as const,
    created_at: "2026-05-25T16:40:00Z",
  },
  {
    id: "r4",
    business_id: "1",
    customer_name: "Amelia W.",
    order_id: "ORD-47856",
    rating_overall: 5,
    review_text: "Google stars showed up in our ads within a week of collecting reviews through EarnedStar.",
    verified_purchase: true,
    fraud_score: 5,
    status: "published" as const,
    created_at: "2026-05-20T11:00:00Z",
  },
];

export const dashboardStats = {
  totalReviews: 2847,
  weeklyDelta: 12,
  avgRating: 4.9,
  pendingResponses: 3,
  fraudBlocked: 47,
};
