// Generated by evalforge fix — smoke test for earnedstar. Extend freely.
"use strict";
const { test } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const pkgPath = path.join(__dirname, "..", "package.json");

function resolveEntry(pkg) {
  if (pkg.main) return pkg.main;
  if (typeof pkg.exports === "string") return pkg.exports;
  if (pkg.exports && typeof pkg.exports === "object") {
    const dot = pkg.exports["."];
    if (typeof dot === "string") return dot;
    if (dot && typeof dot === "object") return dot.require || dot.import || dot.default || null;
  }
  return null;
}

test("package.json parses", () => {
  const raw = fs.readFileSync(pkgPath, "utf8");
  assert.doesNotThrow(() => JSON.parse(raw));
});

test("declared entry resolves or exists on disk", () => {
  const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
  const entry = resolveEntry(pkg);
  if (!entry) return; // nothing declared — the parses-check above is the whole smoke test
  const entryAbs = path.join(__dirname, "..", entry);
  try {
    require(entryAbs);
  } catch {
    // Missing deps or a non-require()-able source (e.g. bare TypeScript
    // without a loader) are expected in some targets — fall back to just
    // asserting the declared entry file exists on disk.
    assert.ok(fs.existsSync(entryAbs), `entry file ${entry} should exist`);
  }
});
