// Generated by evalforge fix — smoke test for earnedstar. Extend freely.
"use strict";
const { test } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const pkgPath = path.join(__dirname, "..", "package.json");

function resolveEntry(pkg) {
  if (pkg.main) return pkg.main;
  if (typeof pkg.exports === "string") return pkg.exports;
  if (pkg.exports && typeof pkg.exports === "object") {
    const dot = pkg.exports["."];
    if (typeof dot === "string") return dot;
    if (dot && typeof dot === "object") return dot.require || dot.import || dot.default || null;
  }
  return null;
}

test("package.json parses", () => {
  const raw = fs.readFileSync(pkgPath, "utf8");
  assert.doesNotThrow(() => JSON.parse(raw));
});

test("declared entry exists on disk", () => {
  const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
  const entry = resolveEntry(pkg);
  if (!entry) return; // nothing declared — the parses-check above is the whole smoke test
  const entryAbs = path.join(__dirname, "..", entry);
  // Existence only — deliberately NOT require()d: importing an entry executes
  // it, and server entries call listen() on import (two fleet targets bound
  // real ports from inside this test before this was changed).
  assert.ok(fs.existsSync(entryAbs), `entry file ${entry} should exist`);
});
