/**
 * Copyright (c) 2024-2026 Expedia Solutions, LLC. All Rights Reserved.
 * Proprietary and confidential. Unauthorized copying, distribution, or use
 * is strictly prohibited without express written permission.
 */
import type { Metadata } from 'next';
import Link from 'next/link';
import { AppJobLink } from '@/components/app/AppJobLink';
import { AppShell } from '@/components/app/AppShell';

export const metadata: Metadata = { title: 'App' };

/** Distilled hub stub — generated by fleet:mobile:distill. Expand jobs; do not dump marketing homepage. */
export default function DistilledAppPage() {
  return (
    <AppShell activePath="/app">
      <header className="mb-2">
        <p className="text-[10px] font-extrabold uppercase tracking-[0.22em] text-gold">
          EarnedStar
        </p>
        <h1 className="text-2xl font-semibold text-white">App</h1>
      </header>
      <p className="text-sm text-gray-400">Thumb-first product surface — not the marketing site</p>
      <nav className="mt-6 grid gap-3" aria-label="Shortcuts">
        <AppJobLink
          href="/app/reviews"
          title="Reviews"
          description="Primary job: reviews"
        />
        <AppJobLink
          href="/app/dashboard"
          title="Seller Dashboard"
          description="Primary job: seller-dashboard"
        />
      </nav>
      <div className="mt-10 border-t border-white/10 pt-6">
        <Link href="/" className="inline-flex min-h-11 items-center text-sm font-bold text-gray-500">
          Full desktop site
        </Link>
      </div>
    </AppShell>
  );
}
